import type { Job } from "../../types/job"
export const mockJobs: Job[] = [
    {
        id: 1,
        title: "Software Engineer",
        company: "OpenAI",
        location: "Remote",
        status: "Applied",
        applied_date: "2025-10-06",
        follow_up_date: null,
        job_link: "https://openai.com/jobs/1",
        job_description: "Work with AI models",
        job_board_id: "12345",
        source: "LinkedIn",
        notes: "Applied through referral",
        created_at: "2025-10-06",
        updated_at: "2025-10-06",
    },
    {
        id: 2,
        title: "Backend Developer",
        company: "Google",
        location: "Mountain View, CA",
        status: "Interview",
        applied_date: "2025-09-20",
        follow_up_date: "2025-09-27",
        job_link: null,
        job_description: "Python backend for cloud services",
        job_board_id: "67890",
        source: "Company Site",
        notes: "Reached out via email",
        created_at: "2025-09-20",
        updated_at: "2025-09-27",
    },
  
    {
        id: 3,
        title: "Software Engineer",
        company: "OpenAI",
        location: "Remote",
        status: "Applied",
        applied_date: "2025-10-01",
        follow_up_date: null,
        job_link: "https://openai.com/careers",
        job_description: "Work on AI stuff",
        job_board_id: "123",
        source: "LinkedIn",
        notes: "First application",
        created_at: "2025-10-01",
        updated_at: "2025-10-01"
    },

    {
        id: 4,
        title: "Software Engineer",
        company: "Google",
        location: "Remote",
        status: "Applied",
        applied_date: "2025-10-02",
        follow_up_date: null,
        job_link: null,
        job_description: "Work on AI stuff",
        job_board_id: "123",
        source: null,
        notes: "Application without link or source",
        created_at: "2025-10-02",
        updated_at: "2025-10-02"
    },

    {
        id: 5,
        title: "Software Engineer",
        company: "Google",
        location: "Remote",
        status: "Applied",
        applied_date: "2025-10-02",
        follow_up_date: null,
        job_link: null,
        job_description: "Work on AI stuff",
        job_board_id: "123",
        source: "LinkedIn",
        notes: "Application without link but has source",
        created_at: "2025-10-02",
        updated_at: "2025-10-02"
    },
]